### ISSUE TITLE
Each protocol conformance implementation should occur in dedicated type extension within the same file as the type

### ISSUE THREAD

**Issue by fdiaz** [airbnb/swift#58]
This rule is missing autocorrect. Following [this PR](https://github.com/airbnb/swift/pull/35).

---

* <a id='extensions-for-protocol-conformance'></a>(<a href='#extensions-for-protocol-conformance'>link</a>)
 **Each protocol conformance implementation should occur in dedicated type extension within the same file as the type.** This extension should be marked with `// MARK: ProtocolName`, and should contain nothing more than the methods or properties required to conform to the protocol. As a result, no `// MARK:`s are needed for defining subsections.

**Comment by calda** [comment]
Closing since this has been open for three years. I like this one personally but its probably intractable to autocomplete -- it would require having full type information available to the formatter tool (not only of the source code files being formatted, but all of their dependencies and the iOS SDKs etc).
